### ISSUE TITLE
Showing double width label

### ISSUE THREAD

**Issue by weiweihuanghuang** [Mark2Mark/Show-Label-Color#3]
![screen shot 2018-03-29 at 3 32 25 pm](https://user-images.githubusercontent.com/1271897/38091647-6bac4718-3366-11e8-9726-048b36ddd591.png)
Recently it started doing this..
Only happens when a glyph has a master *and* label colour.
Version 2.5b (1125)

**Comment by Mark2Mark** [comment]
Thanks for reporting! I’ll have a look …
